config/routes.rb
GodwinRepo::Application.routes.draw do
  

  root 'home#index'

  resources :users, only: [:show, :new] do
    resources :likes, only: [:index]
    resources :comments, only: [:index]
  end
  get '/search' => 'search#index'
  get '/search/results' => 'search#results'
  get "/signout" => "sessions#destroy", :as => :signout
  get '/auth/:provider/callback', :to => 'sessions#omni_create'
  get '/auth/failure', :to => 'sessions#failure'
  
  resources :posts do
    get 'date'
    resources :likes, only: [:create]
    resources :comments, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :index]
  resources :tags, only:[:show, :index]
  resources :sessions, only: [:create, :destroy, :new]

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	has_many :comments_received, through: :posts, source: :comments
	has_many :likes
	has_many :liked_posts, through: :likes, source: :post
	has_many :post_likes_received, through: :posts, source: :likes
	has_many :comment_likes_received, through: :comments, source: :likes
	has_many :authorizations

	#VALIDATIONS
	# validates_uniqueness_of :email
	# validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
	validates_presence_of :name

	#bcrypt stuff
	has_secure_password

  	def add_provider(auth_hash)
  	  unless authorizations.find_by(provider:auth_hash["provider"], uid: auth_hash["uid"])
  	    Authorization.create!(user: self, provider: auth_hash["provider"], uid: auth_hash["uid"])
  	  end
  	end

	def total_likes_given
		# self.comment_likes_given +  self.post_likes_given
	end

	def total_likes_received
		self.comment_likes_received.count +  self.post_likes_received.count
	end

	def total_comments_received
	end

	def total_likers

	end

	def rand_date(days)
  		rand(days).days.ago(Date.today)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	
  end
  
  def show
    @user = User.find(params[:id]) 
    @posts = @user.posts
    if request.xhr?
      build_pie_chart(@user.id)
    else
      render 'show'
    end
  end

end

app/views/users/_chart.html.erb
<img id="omni-img" src="<%=@user.pic%>" alt="" class="img-circle">
<img src="<%=image_path(@user.pic)%>" alt="" class="img-circle">
<div class="charts--container">
  <ul>
    <li class="chart">
      <div id="pieChart">
        <svg id="pieChartSVG">
          <defs>
            <filter id='pieChartInsetShadow'>
              <feOffset dx='0' dy='0'/>
              <feGaussianBlur stdDeviation='3' result='offset-blur' />
              <feComposite operator='out' in='SourceGraphic' in2='offset-blur' result='inverse' />
              <feFlood flood-color='black' flood-opacity='1' result='color' />
              <feComposite operator='in' in='color' in2='inverse' result='shadow' />
              <feComposite operator='over' in='shadow' in2='SourceGraphic' />
            </filter>
            <filter id="pieChartDropShadow">
              <feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur" />
              <feOffset in="blur" dx="0" dy="3" result="offsetBlur" />
              <feMerge>
                <feMergeNode />
                <feMergeNode in="SourceGraphic" />
              </feMerge>
            </filter>
          </defs>
        </svg>
      </div>
    </li>
    <!-- <li class="chart">
      <div id="lineChart">
        <svg id="lineChartSVG" class="lineChart--svg">
          <defs>
            <linearGradient id="lineChart--gradientBackgroundArea" x1="0" x2="0" y1="0" y2="1">
              <stop class="lineChart--gradientBackgroundArea--top" offset="0%" />
              <stop class="lineChart--gradientBackgroundArea--bottom" offset="100%" />
            </linearGradient>
          </defs>
        </svg>
      </div>
    </li> -->
  </ul>
</div>

app/views/users/_new.html.erb
    <%= form_for :user, class: 'form-horizontal', url: sessions_path do |f| %>
    <div class="form-group">
      <%= f.label :name , class: 'col-sm-2'%>
      <div class="col-sm-10">
        <%= f.text_field :name, :placeholder => "Name" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: 'col-sm-2' %>
      <div class="col-sm-10">
        <%= f.text_field :email, :placeholder => "enteryour@email.com" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, class: 'col-sm-2' %>
      <div class="col-sm-10">
        <%= f.text_field :password, :placeholder => "password" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, class: 'col-sm-2' %>
      <div class="col-sm-10">
        <%= f.text_field :password_confirmation, :placeholder => "password confirmation" %>
      </div>
    </div>
    <p>
      <%= f.submit "Signup" %>
      <%= f.submit "Login" %>
    </p>
    <% end %>

app/views/users/_sign_in.html.erb
    <%= form_for :user, html:{class: 'signinform form-inline'}, url: sessions_path do |f| %>
    <p class="form-group">
      <%= f.text_field :email, class: 'form-control', :placeholder => "Email" %>
    </p>
    <p class="">
      <%= f.password_field :password, class: 'form-control', :placeholder => "Password" %>
    </p>
    
    <p class="">
      <%= f.submit "Sign In", class: 'btn btn-primary' %>
    </p>
    <% end %>

app/views/users/new.html.erb
    <%= form_for :user, class: 'form-horizontal', url: sessions_path do |f| %>
    <div class="form-group">
      <%= f.label :name , class: 'col-sm-2 control-label'%>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', :placeholder => "Name" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <hr>
    <div class="form-group">
      <%= f.label :email, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.email_field :email, class: 'form-control', :placeholder => "enteryour@email.com" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <hr>
    <div class="form-group">
      <%= f.label :password, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control', :placeholder => "password" %>
      </div>
    </div>
    <div class="clearfix"></div>
    <hr>
    <div class="form-group">
      <%= f.label :password_confirmation, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, class: 'form-control', :placeholder => "password confirmation" %>
      </div>
    </div>

    <div class="clearfix"></div>
    <hr>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Signup", class: 'btn btn-primary btn-block' %>
    </div>
  </div>
    <% end %>
<div class="clearfix"></div>

app/views/users/show.html.erb
<%= javascript_include_tag params[:controller] %>

<div class="row">
	<div class="col-md-3">
		<h2><%= @user.name.capitalize%>'s Profile</h2>
	</div>
</div><!-- row -->

<div class="row">

	<div class="col-md-3 col-md-offset-1">
		<ul class="user-stats">
			<li><small>User since: </small><%=@user.created_at.strftime("%B %d, %Y")%><!-- user.join_date ? --></li>
			<!-- we should probably either take this our after dev or provide an show/hide email toggle for users -->
			
			<li><small>Twitter: </small> <a href="<%=@user.twitter%>">@RobScharf</a> <!-- @user.twitter ? --></li>
		</ul>
	</div>	
	<div class="col-md-3">
		<ul class="user-stats">
			<li><small>Posts: </small><%=@user.posts.count%><!-- user.post_count ? --> </li>
			<li>
				<%=link_to "User Comments:  #{@user.comments.count}",  user_comments_path(@user.id), class: '' %><!-- user.comment_count ? -->
			</li>
			<li><small>Comments Received: </small><%=@user.comments_received.count%><!-- user.comment_count ? --></li>
		</ul>
	</div>	
	<div class="col-md-3">
		<ul class="user-stats">
			<li>
				<%=link_to "User Likes:  #{@user.likes.count}",  user_likes_path(@user.id), class: '' %>
			</li>
			<li><small>Comments Liked By Others:</small> <%=@user.comment_likes_received.count%></li>
			<li><small>Total Likes Received:</small> <%=@user.total_likes_received%></li>
		</ul>			
	</div>
	<div class="clearfix"></div>
	<hr>
	<div class="col-md-10 col-md-offset-1">
		<%= render "users/chart" %>
	</div>
	<div class="clearfix"></div>
	<hr>
	<h2 class="">Posts</h2>
	<%= render "tags/posts_list" %>
</div><!-- row -->

app/views/users/show2.html.erb
<%= javascript_include_tag 'posts.js' %>

<button id="show-post-form" class="col-md-4 btn btn-lg btn-success">
    <h4>create new post</h4>
</button>

<div class="clearfix"></div>
<hr>

<div id="post-form">
  <%= render "posts/new2" %>  
</div>