config/routes.rb
GodwinRepo::Application.routes.draw do
  

  root 'home#index'

  resources :users, only: [:show, :new] do
    resources :likes, only: [:index]
    resources :comments, only: [:index]
  end
  get '/search' => 'search#index'
  get '/search/results' => 'search#results'
  get "/signout" => "sessions#destroy", :as => :signout
  get '/auth/:provider/callback', :to => 'sessions#omni_create'
  get '/auth/failure', :to => 'sessions#failure'
  
  resources :posts do
    get 'date'
    resources :likes, only: [:create]
    resources :comments, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :index]
  resources :tags, only:[:show, :index]
  resources :sessions, only: [:create, :destroy, :new]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.popular.limit(9)
  end
end

app/views/home/_basic_nav.html.erb
<ul class="nav nav-pills pull-right">
  <li class="<%= is_active?(root_url) %>">
    <%= link_to "Home", root_url%>
  </li>
  <li class="<%= is_active?(page_path('about')) %>">
    <%= link_to "About", page_path("about") %>
  </li>
  <li class="<%= is_active?(tags_path) %>">
    <%= link_to "Index", tags_path %>
  </li>
  <li class="<%= is_active?(categories_path) %>">
    <%= link_to "Categories", categories_path %>
  </li>
  <li class="<%= is_active?(posts_path) %>">
    <%= link_to "Posts", posts_path %>
  </li>
  <li class="<%= is_active?(search_path) %>">
    <%= link_to "Search", search_path %>
  </li>
</ul>

app/views/home/_footer.html.erb
<hr>
<footer class="text-center bg-info">
  <p>&copy; Rob Scharf and Nick Smit - 2014</p>
</footer>

app/views/home/_legend.html.erb
<div class="row home-row categories">
	<h2 class="home-title">Categories</h2>
	<div class="clearfix"></div>
	<% Category.all.each do |cat| %>
		<div class="col-lg-4">
			<h5>
				<%if cat.key == "WLP"%>
					<%= link_to '', category_path(cat.id), class: "btn btn-lg btn-primary" %>
				<%elsif cat.key == "CML"%>
					<%= link_to '', category_path(cat.id), class: "btn btn-lg btn-warning" %>
				<%elsif cat.key == "PPP"%>
					<%= link_to '', category_path(cat.id), class: "btn btn-lg btn-success" %>
				<%elsif cat.key == "CP"%>
					<%= link_to '', category_path(cat.id), class: "btn btn-lg btn-danger" %>
				<%elsif cat.key == "PJN"%>
					<%= link_to '', category_path(cat.id), class: "btn btn-lg btn-info" %>
				<%elsif cat.key == "M"%>
					<%= link_to '', category_path(cat.id), class: "btn btn-lg btn-extra" %>
				<%end%>
				<%= link_to cat.title, category_path(cat.id) %>
			</h5>
		</div>
	<%end%>
</div>

app/views/home/_sign_in_out_nav.html.erb
 <ul class="signuporin pull-right">
   <% if current_user %>
   <li>
     <button id="show_post_form" class="btn btn-default btn-block">
       Create Post
     </button>
     <div id="post_form" class="col-md-12 hidden">
       <%= render "posts/new" %>
     </div>
   </li>
   <li>
     <%= link_to "Profile Page", user_path(current_user.id), class: 'btn btn-success' %>
       <%= link_to "Log out", session_path(current_user.id), method: :delete, class: 'btn btn-default' %>
   </li>   
 <% else %>
   <li>
     <%= render "users/sign_in" %>
  </li>
  <li>
   <%= link_to "Sign Up", new_user_path, class: ' btn btn-default' %>
  </li>
  <li>
    <%= link_to 'Sign in With Facebook', '/auth/facebook', class: 'btn btn-info' %>
  </li>
    <%= link_to 'Sign in With Github', '/auth/github', class: 'btn btn-default' %>
  <li>
  <li>
      <%= link_to 'Sign in With Twitter', '/auth/twitter', class: 'btn btn-danger' %>
  </li>
  <%end%>
 </li>
 </ul>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1>The Godwin Repository</h1>
	<p class="lead">Your source for all things "literally Hitler" on the web.</p>

</div>

<%= render "home/legend" %>

<div class="row home-row recent-posts">
		<h2 class="home-title">Most popular entries</h2>
		<%= render "tags/posts_list" %>
		
</div><!-- row -->

<div class="row home-row help">
		<h2 class="home-title">Having trouble finding what you're looking for?</h2>
		<div class="clearfix"></div>
		
		<div class="col-md-10 col-md-offset-1"> 
			<p>You have a few options. The best way to find a list of entries relating to an individual or organization is to locate him, her, or it on the <a href="#">alphabetized master list</a> of people and organizations in our database! Alternatively, you could check out the <a href="#">most recent submissions</a> or try a keyword search in the area provided at the top-right of the page.</p>
		</div>
		
</div>


 