config/routes.rb
GodwinRepo::Application.routes.draw do
  

  root 'home#index'

  resources :users, only: [:show, :new] do
    resources :likes, only: [:index]
    resources :comments, only: [:index]
  end
  get '/search' => 'search#index'
  get '/search/results' => 'search#results'
  get "/signout" => "sessions#destroy", :as => :signout
  get '/auth/:provider/callback', :to => 'sessions#omni_create'
  get '/auth/failure', :to => 'sessions#failure'
  
  resources :posts do
    get 'date'
    resources :likes, only: [:create]
    resources :comments, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :index]
  resources :tags, only:[:show, :index]
  resources :sessions, only: [:create, :destroy, :new]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.order('title')
  end

  def show
  	@tag = Tag.find(params[:id])
  	@posts = @tag.posts
  end

end

app/views/tags/_posts_list.html.erb
<% @posts.each_slice(3) do |post_slice| %>
		<% post_slice.each do |post| %>
			<div class="col-md-4">
			 	<div class="recent-entry">
					<%= render partial: 'posts/accusation', locals: {post: post}  %>
					
						<p class="post-excerpt"><%= truncate(post.quote, length: 93) %> 
							<small>
								<%= link_to '(view full entry)', post_path(post.id) %>		
							</small>
						</p>
						
						<h4 class="">
							<small>
								By: <%= link_to post.user.name.capitalize, user_path(post.user.id) %>
							</small>
							<small class="pull-right">
								</button> Date: <%= link_to post.event_date, post_date_path(post), class: "" %>
							</small> 
						</h4>
					<hr>
					<% post.tags.each do |tag|%>
							<%= link_to tag.title.capitalize, tag_path(tag.id), class: 'btn btn-sm btn-default' %>
					<%end%>
						<%= render partial: 'likes/new', locals: {post: post} %>					
					<hr>
				</div><!-- recent entry -->
			</div><!--col 4 -->
		<% end %>
		<div class="clearfix"></div>

<% end %>

app/views/tags/index.html.erb
<h1>
  Tags List
</h1>
<hr>
<div id="searcharea">
  <input type="search" name="search" id="search" class="form-control" placeholder="Search Tags" />
</div>
<div class="clearfix"></div>
<hr>
<div id="update">
  <% @tags.each do |tag| %>
        <%= link_to tag.title.capitalize, tag_path(tag.id), class: 'btn btn-md btn-default' %>
  <% end %>
</div>

<%= javascript_include_tag 'tags.js' %>

app/views/tags/show.html.erb
<div class="row">
	<button type="button" class="btn-info btn btn-lg"> <%= @tag.title %></button>
	<h3>
		Posts
	</h3>
<%= render "tags/posts_list" %>
		
</div><!-- row -->