config/routes.rb
GodwinRepo::Application.routes.draw do
  

  root 'home#index'

  resources :users, only: [:show, :new] do
    resources :likes, only: [:index]
    resources :comments, only: [:index]
  end
  get '/search' => 'search#index'
  get '/search/results' => 'search#results'
  get "/signout" => "sessions#destroy", :as => :signout
  get '/auth/:provider/callback', :to => 'sessions#omni_create'
  get '/auth/failure', :to => 'sessions#failure'
  
  resources :posts do
    get 'date'
    resources :likes, only: [:create]
    resources :comments, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :index]
  resources :tags, only:[:show, :index]
  resources :sessions, only: [:create, :destroy, :new]

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :accuser
	belongs_to :accused
	has_many :comments
	has_many :likes
	has_many :likers, through: :likes, source: :user
	has_one :accuser_category, through: :accuser, source: :category
	has_one :accused_category, through: :accused, source: :category
	
	has_and_belongs_to_many :tags
	
	scope :popular, -> { order('likes_count DESC') }
      # accepts_nested_attributes_for :accuser, :accused
	# has_and_belongs_to_many :categories
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end
  
  def new
  	
  end

  def show
  	@post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @posts = Post.find_all_by(event_date:params[:post])
    @posts = Post.popular
  end
  
  def new
    
  end

  def create
    @post = Post.create(post_params)
    build_relationships(params, @post.id)
    redirect_to post_path(@post.id)
  end

  def show  
    @post = Post.find(params[:id]) 
  end

  def destroy
    Post.destroy(params[:id])
    redirect_to user_path(current_user.id)  
  end

  def edit
    @post = Post.find(params[:id])    
  end

  def update
    post_update(params)
    redirect_to user_path(current_user.id)
  end
  
  def date
    @posts = Post.find_all_by_event_date(Post.find(params[:post_id]).event_date)
    render "tags/_posts_list"
  end

  private
    def post_params
      params.require(:post).permit(:user_id, :url, :quote, :context, :event_date)
    end

end

app/helpers/post_helper.rb
module PostHelper
  
  def randoms
    rand_string = ('a'..'z').to_a + (0..9).to_a*3
    rand_string.shuffle[0...6].join
  end

end

app/views/posts/_accusation.html.erb
<div class="accusation">
  <h4>
    <% if post.accuser.category.key == "WLP" %>
      <%= link_to post.accuser.title, category_path(post.accuser.category.id), class: "btn btn-sm btn-primary" %> 
      <% elsif post.accuser.category.key == "CML" %>
        <%= link_to post.accuser.title, category_path(post.accuser.category.id), class: "btn btn-sm btn-warning" %>
      <% elsif post.accuser.category.key == "PPP" %>
        <%= link_to post.accuser.title, category_path(post.accuser.category.id), class: "btn btn-sm btn-success" %>
      <% elsif post.accuser.category.key == "CP" %>
        <%= link_to post.accuser.title, category_path(post.accuser.category.id), class: "btn btn-sm btn-danger" %>
      <% elsif post.accuser.category.key == "PJN" %>
        <%= link_to post.accuser.title, category_path(post.accuser.category.id), class: "btn btn-sm btn-info" %>
      <% elsif post.accuser.category.key == "M" %>
        <%= link_to post.accuser.title, category_path(post.accuser.category.id), class: "btn btn-sm btn-info" %>  
    <% end %>
    <small> invoked Godwin's Law against... </small>
    <% if post.accused.category.key == "WLP" %>
      <%= link_to post.accused.title, category_path(post.accused.category.id), class: "btn btn-sm btn-primary" %> 
      <% elsif post.accused.category.key == "CML" %>
        <%= link_to post.accused.title, category_path(post.accused.category.id), class: "btn btn-sm btn-warning" %>
      <% elsif post.accused.category.key == "PPP" %>
        <%= link_to post.accused.title, category_path(post.accused.category.id), class: "btn btn-sm btn-success" %>
      <% elsif post.accused.category.key == "CP" %>
        <%= link_to post.accused.title, category_path(post.accused.category.id), class: "btn btn-sm btn-danger" %>
      <% elsif post.accused.category.key == "PJN" %>
        <%= link_to post.accused.title, category_path(post.accused.category.id), class: "btn btn-sm btn-info" %>
      <% elsif post.accused.category.key == "M" %>
        <%= link_to post.accused.title, category_path(post.accused.category.id), class: "btn btn-sm btn-extra" %>  
    <% end %>
  </h4>
</div><!-- accusation -->

app/views/posts/_new.html.erb
    <%= form_for Post.new, class: 'form-horizontal center', url: posts_path do |f| %>
      <% f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group">
        <%= f.label 'accuser', class: 'col-sm-2 control-label'%>
        <div class="col-sm-6">
          <%= f.text_field :accuser, required: true, class: 'form-control', :placeholder => "Accuser" %>
        </div>
        <%= f.label 'Accuser Category', class: 'col-sm-2 control-label'%>
        <div class="col-sm-1">
          <%= f.collection_select :accuser_category, Category.all, :id, :title %>
        </div>
      </div>
      <div class="clearfix"></div>
      
      <div class="form-group">
        <%= f.label 'Accused', class: 'col-sm-2 control-label'%>
        <div class="col-sm-6">
          <%= f.text_field  :accused, required: true, class: 'form-control', placeholder: 'Accused' %>
        </div>
        <%= f.label 'Accused Category', class: 'col-sm-2 control-label'%>
        <div class="col-sm-1">
          <%= f.collection_select :accused_category, Category.all, :id, :title %>
        </div>
      </div>  
      
      <div class="clearfix"></div>
      

      <div class="form-group">
        <%= f.label :url, class: 'col-sm-2 control-label'%>
        <div class="col-sm-6">
          <%= f.text_field :url, required: true, class: 'form-control', :placeholder => "www.post.url" %>
        </div>
        <%= f.label 'Date', class: 'col-sm-1 control-label'%>
        <div class="col-sm-3">
          <%= f.text_field  :event_date, required: true, class: 'form-control datepicker' %>
        </div>
      </div>  
      <div class="clearfix"></div>
          
      
      <div class="form-group">
        <%= f.label :quote, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :quote, required: true, class: 'form-control', :placeholder => "quote" %>
        </div>
      </div>
      <div class="clearfix"></div>
      
      <div class="form-group">
        <%= f.label :context, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :context, required: true, class: 'form-control', :placeholder => "context" %>
        </div>
      </div>
      <div class="clearfix"></div>
      <hr>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <button id="unshow_post_form" class="btn btn-danger btn-block">Cancel</button>
        </div>
        <div class=" col-sm-10">
        <%= f.submit "Post", class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>
<div class="clearfix"></div>
<hr>

app/views/posts/edit.html.erb
<%= javascript_include_tag 'posts.js' %>
<h1>
  whos your daddy
</h1>

    <%= form_for @post, class: 'form-horizontal center' do |f| %>
      
      <div class="form-group">
        <%= f.fields_for @post.accuser do |accuser_f| %>
          <%= accuser_f.label 'accuser', class: 'col-sm-2 control-label'%>
          <div class="col-sm-6">
            <%= accuser_f.text_field :title, required: true, class: 'form-control', :placeholder => "Accuser" %>
          </div>
          <%= accuser_f.label 'Accuser Category', class: 'col-sm-2 control-label'%>
          <div class="col-sm-1">
            <%= accuser_f.collection_select :category, Category.all, :id, :title, {:selected=> @post.accuser.category.title.to_s }  %>
          </div>
          

        <% end %>
      </div><!-- FORM GROUP FOR ACCUSER CLOSE -->

      <div class="clearfix"></div>
      
      <div class="form-group">
        <%= f.fields_for @post.accused do |accused_f| %>
          <%= accused_f.label 'accused', class: 'col-sm-2 control-label'%>
          <div class="col-sm-6">
            <%= accused_f.text_field :title, required: true, class: 'form-control', :placeholder => "Accused" %>
          </div>
          <%= accused_f.label 'Accused Category', class: 'col-sm-2 control-label'%>
          <div class="col-sm-1">
            <%= accused_f.collection_select :category, Category.all, :id, :title,  {:selected=> @post.accused.category.title.to_s} %>
          </div>
        <% end %>
      </div><!-- FORM GROUP FOR ACCUSER CLOSE -->

      <div class="clearfix"></div>
      
      <div class="form-group">
        <%= f.label :url , class: 'col-sm-2 control-label'%>
        <div class="col-sm-6">
          <%= f.text_field :url, required: true, class: 'form-control', :placeholder => "" %>
        </div>
        <%= f.label 'Date', class: 'col-sm-1 control-label'%>
        <div class="col-sm-3">
          <%= f.text_field  :event_date, required: true, class: 'form-control datepicker' %>
        </div>
      </div>  
      <div class="clearfix"></div>
      
      <div class="form-group">
        <%= f.label :quote, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :quote, required: true, class: 'form-control', :placeholder => "quote" %>
        </div>
      </div>
      <div class="clearfix"></div>
      
      <div class="form-group">
        <%= f.label :context, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :context, required: true, class: 'form-control', :placeholder => "context" %>
        </div>
      </div>
      <div class="clearfix"></div>
      <hr>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= link_to "Cancel", post_path(@post.id), method: :get, action: :show, class: 'btn btn-block btn-danger' %>
        </div>
        <div class=" col-sm-10">
        <%= f.submit "Post", class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>
<div class="clearfix"></div>
<hr>

app/views/posts/index.html.erb
<h1>Posts Arranged by Popular</h1>
<hr>
<div id="searcharea">
  <input type="search" name="search" id="search" class="form-control" placeholder="Search Posts" />
</div>
<div class="clearfix"></div>
<hr>
<div id="update">
<%= render 'tags/posts_list' %>
</div>

<%= javascript_include_tag 'posts.js' %>

app/views/posts/show.html.erb
<% if current_user == @post.user %>
  <div class="row">
    <div class="col-md-2">
      <%= button_to "Delete Post", { action: "destroy", id: @post.id }, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn-danger  btn btn-block' %>    
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= button_to 'Edit Post', edit_post_path(@post.id), method: :get,  class: 'btn btn-info btn-block'  %>
    </div>  
  </div>
<%end%>

      <div class="row quote">
        <div class="col-md-2 col-md-offset-9">
          <%= render partial: 'likes/new', locals: {post: @post} %>
        </div>
        <div class="col-md-8 col-md-offset-2 btn-sm excerpt">
          <h3><%= @post.quote %></h3>
        </div>
      </div> <!-- row -->

      <div class="row details top-margin">
        
        <div class="col-md-8 col-md-offset-2 details-text">
          <h4><%= link_to @post.accuser.title, tag_path(Tag.find_by(title: @post.accuser.title)) %> invoked Godwin's Law against <%= link_to @post.accused.title, tag_path(Tag.find_by(title: @post.accused.title)) %> on <%= link_to @post.event_date, post_date_path(@post), class: "" %>.</h4>
        </div>   
        
      </div><!-- row details -->

      <div class="row context top-margin">
        <div class="col-md-8 col-md-offset-2 context-text">
          <h4>Context:<small><%= @post.context %></small></h4> <!-- !!  need post.context !! -->
        </div>   
      </div>

      <hr>

      <div class="row">
        <div class="col-lg-8 col-md-offset-1">
          <h4>Liked By: 
          <%@post.likers.each do |liker| %>
          <span class="glyphicon glyphicon-star"></span> 
            <%= link_to liker.name.capitalize, user_path(liker.id), class: "" %>
          <%end%>
          </h4>  
        </div>
      </div>

      <div class="row author">
        
        <div class="col-md-5 col-md-offset-1">
          <h4> Submitted by:
          <span class="glyphicon glyphicon-star"></span> <%= link_to @post.user.name.capitalize, user_path(@post.user.id) %>
          </h4>
          <h4>
            URL: <a href="<%= @post.url %>">Source Link</a> 
          </h4>
        </div>
      </div><!-- row author -->
      
      <hr>

    <div class="row comment-title">
      <div class="col-md-5 col-md-offset-1">
        <h3>Comments:</h3>
      </div>
    </div>
    <% @post.comments.each do |comment| %>
    <div class="row comments">  
      <div class="col-md-8 comment col-md-offset-2">  
        <h4 class="comment-author">
          <%= link_to comment.user.name.capitalize, user_path(comment.user.id) %>
        </h4>
        
        
        <blockquote>
          <p class="comment-text">
            <%= comment.content %>
        <% if current_user == comment.user %>
          <span class="">
            <%= button_to 'Delete', post_comment_path(@post.id, comment.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn-danger  btn-sm' %> 
          </span>
        <% end %>
          </p>
       </blockquote> 
      </div><!-- comment-->
    </div>
    <% end %>
    <% if current_user %>
      <div id="comment_form" >
        <%= render partial: 'comments/new', locals: { post: @post } %>
      </div>
      <% end %>